### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by awinecki** [dlvhdr/gh-prs#10]
Looks amazing – can't wait to test it out! Though it doesn't seem to work on m1 macs yet..

**Comment by dlvhdr** [comment]
Oh bummers.. I don't have an m1, what error are you getting?

**Comment by VictorBersy** [comment]
Not much information unfortunately:

```
$ gh extension install dlvhdr/gh-prs
gh-prs unsupported for darwin-arm64. Open an issue: `gh issue create -R dlvhdr/gh-prs -t'Support darwin-arm64'`
```

But I think it's because there is no assets called `darwin-arm64` in the releases assets, based on what I understand from https://github.com/cli/cli/blob/b5d90e120405ee5a7fe6dfdcc58f1eeffbb9f88c/pkg/cmd/extension/manager.go#L360-L364

And also from what I understand, the Github action used to release this project does not support anymore a list of custom platform to build for (https://github.com/cli/gh-extension-precompile/commit/e482de81ba51ed9e200a167c933f792c2956c66c, related discussion: https://github.com/cli/gh-extension-precompile/issues/2)

I've opened a PR on their project so it will build for `darwin-arm64` platform: https://github.com/cli/gh-extension-precompile/pull/3

**Comment by dlvhdr** [comment]
Thanks @VictorBersy that's a lot of good info you researched.. Yeah you understood correctly, I just use the github action, I don't know how to personally compile to different targets, so that was an easy solution for this.

**Comment by VictorBersy** [comment]
Let's see if they accept my PR or not. Meanwhile, if you want to publish it ASAP for ARM Mac, you could try to use an older version of the Github Action:

```yaml
- uses: cli/gh-extension-precompile@v1.0.4
  with:
    platforms: "darwin-amd64,darwin-arm64,linux-386,linux-arm,linux-amd64,linux-arm64,windows-386,windows-amd64"
```

But that's not very future proof as the latest version won't be used.

**Comment by dlvhdr** [comment]
I think it should be fixed now, thanks to @abdfnx, can you check?

**Comment by VictorBersy** [comment]
Yes I was able to install it, thanks a lot!

**Comment by abdfnx** [comment]
> Yes I was able to install it, thanks a lot!

good news

**Comment by joelazar** [comment]
@dlvhdr, could you provide a binary for `linux-amd64` too?

**Comment by abdfnx** [comment]
> @dlvhdr, could you provide a binary for `linux-amd64` too?

you got it

**Comment by abdfnx** [comment]
@joelazar can you try it now ?

**Comment by joelazar** [comment]
working like a charm :) thanks for the quick fix!

**Comment by abdfnx** [comment]
> working like a charm :) thanks for the quick fix!

anytime bro, and thanks @dlvhdr for building this great extension

**Comment by awinecki** [comment]
@dlvhdr confirming it works! ❤️ soo amazing! Sorry for not replying before. Anyway, can't wait to start using this CLI. Thank you!

**Comment by mislav** [comment]
Thanks everyone for your patience and for sharing temporary workarounds!

The [latest GitHub CLI 2.8.0 release](https://github.com/cli/cli/releases/tag/v2.8.0) fixes this by falling back to `amd64` binary if Rosetta is installed. If an `arm64` binary is found, for example as a product of the [latest gh-extension-precompile action](https://github.com/cli/gh-extension-precompile/releases/tag/v1.1.2), however, then its codesigning is fixed after downloading to allow execution by the OS.
